"""Shared constants for the theory-enhanced profiling platform."""

FIELD_ROLES = [
    "ignore",
    "customer_id",
    "household_id",
    "account_id",
    "company_id",
    "existing_segment",
    "age",
    "gender",
    "income",
    "education",
    "occupation",
    "marital_status",
    "household_structure",
    "life_stage",
    "socioeconomic_status",
    "country",
    "region",
    "city",
    "postcode",
    "geographic_area",
    "urban_rural",
    "language",
    "climate_or_environment",
    "interest",
    "lifestyle",
    "values_attitudes",
    "motivation",
    "pain_point",
    "benefit_sought",
    "price_sensitivity",
    "brand_affinity",
    "innovation_adoption",
    "satisfaction",
    "nps",
    "monetary_value",
    "purchase_frequency",
    "recency",
    "avg_order_value",
    "profitability",
    "clv_or_ltv",
    "loyalty",
    "subscription",
    "tenure",
    "product_usage",
    "product_interest",
    "category_preference",
    "engagement",
    "session_activity",
    "page_view",
    "click_activity",
    "email_engagement",
    "social_engagement",
    "app_engagement",
    "funnel_stage",
    "conversion_or_response",
    "campaign_exposure",
    "promotion_usage",
    "channel",
    "device_platform",
    "risk_or_friction",
    "cart_abandonment",
    "churn_indicator",
    "return_refund",
    "complaint_support",
    "cancellation",
    "unsubscribe",
    "failed_payment",
    "negative_feedback",
    "industry",
    "company_size",
    "annual_revenue",
    "employee_count",
    "department",
    "job_title",
    "seniority",
    "decision_role",
    "technology_stack",
    "contract_value",
    "renewal_date",
    "account_health",
    "date_or_time",
    "binary_target",
    "numeric_target",
    "free_text",
    "unknown",
]

POLARITIES = ["positive", "negative", "neutral", "unknown"]

SCORE_GROUPS = {
    "identity_completeness_score": ["customer_id", "household_id", "account_id", "company_id"],
    "demographic_richness_score": [
        "age",
        "gender",
        "income",
        "education",
        "occupation",
        "life_stage",
        "household_structure",
    ],
    "geographic_richness_score": ["country", "region", "city", "postcode", "geographic_area", "urban_rural"],
    "psychographic_richness_score": [
        "interest",
        "lifestyle",
        "values_attitudes",
        "motivation",
        "pain_point",
        "benefit_sought",
        "price_sensitivity",
        "brand_affinity",
        "satisfaction",
        "nps",
    ],
    "value_score": ["monetary_value", "avg_order_value", "profitability", "clv_or_ltv", "contract_value"],
    "frequency_loyalty_score": ["purchase_frequency", "loyalty", "subscription", "tenure", "product_usage"],
    "engagement_score": [
        "engagement",
        "session_activity",
        "page_view",
        "click_activity",
        "email_engagement",
        "social_engagement",
        "app_engagement",
        "product_interest",
    ],
    "conversion_score": ["conversion_or_response", "promotion_usage", "binary_target", "numeric_target"],
    "risk_score": [
        "recency",
        "risk_or_friction",
        "cart_abandonment",
        "churn_indicator",
        "return_refund",
        "complaint_support",
        "cancellation",
        "unsubscribe",
        "failed_payment",
        "negative_feedback",
    ],
    "b2b_account_fit_score": [
        "industry",
        "company_size",
        "annual_revenue",
        "employee_count",
        "technology_stack",
        "contract_value",
        "account_health",
    ],
    "profile_quality_score": [
        "monetary_value",
        "purchase_frequency",
        "recency",
        "engagement",
        "conversion_or_response",
        "risk_or_friction",
        "age",
        "gender",
        "income",
        "country",
        "region",
        "city",
        "interest",
        "lifestyle",
        "satisfaction",
        "industry",
        "company_size",
    ],
}

DEFAULT_POLARITY_BY_ROLE = {
    "monetary_value": "positive",
    "avg_order_value": "positive",
    "profitability": "positive",
    "clv_or_ltv": "positive",
    "purchase_frequency": "positive",
    "loyalty": "positive",
    "subscription": "positive",
    "tenure": "positive",
    "product_usage": "positive",
    "engagement": "positive",
    "session_activity": "positive",
    "page_view": "positive",
    "click_activity": "positive",
    "email_engagement": "positive",
    "social_engagement": "positive",
    "app_engagement": "positive",
    "conversion_or_response": "positive",
    "promotion_usage": "positive",
    "campaign_exposure": "positive",
    "product_interest": "positive",
    "category_preference": "positive",
    "satisfaction": "positive",
    "nps": "positive",
    "account_health": "positive",
    "contract_value": "positive",
    "annual_revenue": "positive",
    "employee_count": "positive",
    "company_size": "positive",
    "binary_target": "positive",
    "numeric_target": "positive",
    "recency": "negative",
    "cart_abandonment": "negative",
    "risk_or_friction": "negative",
    "churn_indicator": "negative",
    "return_refund": "negative",
    "complaint_support": "negative",
    "cancellation": "negative",
    "unsubscribe": "negative",
    "failed_payment": "negative",
    "negative_feedback": "negative",
}

NEUTRAL_ROLES = {
    "ignore",
    "customer_id",
    "household_id",
    "account_id",
    "company_id",
    "existing_segment",
    "age",
    "gender",
    "income",
    "education",
    "occupation",
    "marital_status",
    "household_structure",
    "life_stage",
    "socioeconomic_status",
    "country",
    "region",
    "city",
    "postcode",
    "geographic_area",
    "urban_rural",
    "language",
    "climate_or_environment",
    "interest",
    "lifestyle",
    "values_attitudes",
    "motivation",
    "pain_point",
    "benefit_sought",
    "price_sensitivity",
    "brand_affinity",
    "innovation_adoption",
    "industry",
    "department",
    "job_title",
    "seniority",
    "decision_role",
    "technology_stack",
    "renewal_date",
    "channel",
    "device_platform",
    "funnel_stage",
    "date_or_time",
    "free_text",
    "unknown",
}

DEMOGRAPHIC_ROLES = {
    "age",
    "gender",
    "income",
    "education",
    "occupation",
    "marital_status",
    "household_structure",
    "life_stage",
    "socioeconomic_status",
}

GEOGRAPHIC_ROLES = {
    "country",
    "region",
    "city",
    "postcode",
    "geographic_area",
    "urban_rural",
    "language",
    "climate_or_environment",
}

PSYCHOGRAPHIC_ROLES = {
    "interest",
    "lifestyle",
    "values_attitudes",
    "motivation",
    "pain_point",
    "benefit_sought",
    "price_sensitivity",
    "brand_affinity",
    "innovation_adoption",
    "satisfaction",
    "nps",
}

BEHAVIOURAL_ROLES = {
    "monetary_value",
    "purchase_frequency",
    "recency",
    "avg_order_value",
    "profitability",
    "clv_or_ltv",
    "loyalty",
    "subscription",
    "tenure",
    "product_usage",
    "product_interest",
    "category_preference",
    "engagement",
    "session_activity",
    "page_view",
    "click_activity",
    "email_engagement",
    "social_engagement",
    "app_engagement",
    "funnel_stage",
    "conversion_or_response",
    "campaign_exposure",
    "promotion_usage",
    "channel",
    "device_platform",
    "risk_or_friction",
    "cart_abandonment",
    "churn_indicator",
    "return_refund",
    "complaint_support",
    "cancellation",
    "unsubscribe",
    "failed_payment",
    "negative_feedback",
}

B2B_ROLES = {
    "company_id",
    "account_id",
    "industry",
    "company_size",
    "annual_revenue",
    "employee_count",
    "department",
    "job_title",
    "seniority",
    "decision_role",
    "technology_stack",
    "contract_value",
    "renewal_date",
    "account_health",
}

IDENTITY_ROLES = {"customer_id", "household_id", "account_id", "company_id"}
TARGET_ROLES = {"binary_target", "numeric_target"}
RISK_ROLES = set(SCORE_GROUPS["risk_score"])

PROFILE_DIMENSIONS = {
    "Demographic and socioeconomic": {
        "roles": DEMOGRAPHIC_ROLES,
        "missing": ["age band", "gender", "income band", "education", "life stage"],
        "suggest": "Collect age bands, income bands, household/life-stage, education, and occupation where appropriate.",
    },
    "Geographic and environmental": {
        "roles": GEOGRAPHIC_ROLES,
        "missing": ["region", "city", "delivery zone", "urban/rural"],
        "suggest": "Collect region, city, delivery/store area, and market coverage fields.",
    },
    "Psychographic and motivational": {
        "roles": PSYCHOGRAPHIC_ROLES,
        "missing": ["interests", "motivations", "benefit sought", "satisfaction/NPS", "price sensitivity"],
        "suggest": "Collect survey, NPS, benefit-sought, price-sensitivity, and preference fields.",
    },
    "Behavioural, digital and transactional": {
        "roles": BEHAVIOURAL_ROLES,
        "missing": ["spend", "frequency", "recency", "engagement", "conversion", "risk/friction"],
        "suggest": "Collect purchase value, frequency, recency, funnel, product interest, risk, and response fields.",
    },
    "B2B firmographic and decision-role": {
        "roles": B2B_ROLES,
        "missing": ["industry", "company size", "contract value", "decision role", "technology stack"],
        "suggest": "Collect industry, company size, employee count, contract value, account health, and buying-role fields.",
    },
}

ROLE_KEYWORDS = {
    "customer_id": ["customer_id", "user_id", "client_id", "member_id", "contact_id", "cust_no", "customer_no"],
    "household_id": ["household_id", "family_id"],
    "account_id": ["account_id", "acct_id"],
    "company_id": ["company_id", "firm_id", "organisation_id", "organization_id"],
    "existing_segment": [
        "segment",
        "segment_label",
        "tier",
        "level",
        "class",
        "grade",
        "rank",
        "membership_level",
        "loyalty_tier",
        "customer_group",
        "customer_type",
        "cohort",
        "cluster",
    ],
    "age": ["age", "age_group", "age_band"],
    "gender": ["gender", "sex"],
    "income": ["income", "income_band", "salary"],
    "education": ["education", "degree"],
    "occupation": ["occupation", "job", "profession", "employment"],
    "marital_status": ["marital", "married"],
    "household_structure": ["household", "family_size", "children"],
    "life_stage": ["life_stage", "student"],
    "socioeconomic_status": ["socioeconomic", "social_class"],
    "country": ["country"],
    "region": ["region", "state", "province", "county", "district"],
    "city": ["city"],
    "postcode": ["postcode", "postal_code", "zip"],
    "geographic_area": ["location", "area", "latitude", "longitude", "store_area", "delivery_zone", "headquarters"],
    "urban_rural": ["urban", "rural"],
    "language": ["language", "locale"],
    "climate_or_environment": ["climate", "environment"],
    "interest": ["interest", "hobby"],
    "lifestyle": ["lifestyle"],
    "values_attitudes": ["values", "attitude", "sustainability", "eco", "sentiment"],
    "motivation": ["motivation", "motive", "need", "need_state"],
    "pain_point": ["pain_point", "pain", "barrier"],
    "benefit_sought": ["benefit", "benefit_sought"],
    "price_sensitivity": ["price_sensitive", "price_sensitivity"],
    "brand_affinity": ["brand_affinity", "preferred_brand"],
    "innovation_adoption": ["innovation", "early_adopter"],
    "satisfaction": ["satisfaction", "csat"],
    "nps": ["nps"],
    "monetary_value": [
        "monetary",
        "spend",
        "spending",
        "revenue",
        "sales",
        "sales_value",
        "total_sales",
        "amount",
        "total_amount",
        "order_value",
        "basket_value",
        "value",
    ],
    "avg_order_value": ["avg_order_value", "average_order_value", "aov"],
    "profitability": ["profit", "margin", "profitability"],
    "clv_or_ltv": ["lifetime_value", "clv", "ltv"],
    "contract_value": ["contract_value", "annual_value", "arr", "mrr"],
    "purchase_frequency": [
        "frequency",
        "order_count",
        "orders",
        "purchase_count",
        "purchases",
        "transactions",
        "txn_count",
        "buying_times",
        "repeat_purchase",
        "repeat_orders",
    ],
    "loyalty": ["loyalty_points", "points", "loyalty"],
    "tenure": ["tenure", "membership_years"],
    "subscription": ["subscription", "renewal"],
    "product_usage": ["product_usage", "usage", "active_days"],
    "recency": [
        "recency",
        "days_since",
        "days_from",
        "last_purchase_gap",
        "last_order_gap",
        "inactive_days",
        "days_inactive",
        "time_since_last",
        "last_seen_gap",
        "last_visit_gap",
    ],
    "date_or_time": ["date", "time", "created_at", "updated_at", "joined_at", "signup_date", "first_purchase", "last_purchase"],
    "session_activity": ["session", "sessions", "login", "logins", "app_open", "visit_duration"],
    "page_view": ["page_view", "page_views", "pages_viewed"],
    "click_activity": ["click", "clicks"],
    "email_engagement": ["email_open", "email_click", "open_rate"],
    "social_engagement": ["social_like", "share", "comment"],
    "app_engagement": ["app_engagement", "app_active", "app_open"],
    "engagement": ["engagement", "duration", "dwell_time", "time_on_site", "impression", "impressions"],
    "conversion_or_response": [
        "campaign_response",
        "response",
        "responded",
        "conversion",
        "converted",
        "purchase_flag",
        "bought",
        "purchased",
        "redemption",
        "redeemed",
        "lead",
        "acquisition",
        "sign_up",
        "signup",
        "trial_started",
        "trial_converted",
    ],
    "promotion_usage": ["promo_used", "coupon_used", "promotion", "discount_used"],
    "campaign_exposure": ["campaign", "exposure", "impression"],
    "channel": ["channel", "source", "medium", "referral", "acquisition_channel", "traffic_source"],
    "device_platform": ["device", "platform", "browser", "os"],
    "product_interest": ["wishlist", "wish_list", "favourite", "favorite", "saved_item", "viewed_category"],
    "category_preference": ["category", "product_category", "brand", "preference"],
    "cart_abandonment": ["cart_abandon", "basket_abandon", "abandon", "abandonment"],
    "churn_indicator": ["churn", "churn_risk"],
    "return_refund": ["return", "returns", "refund", "refunds"],
    "complaint_support": ["complaint", "complaints", "support_ticket"],
    "cancellation": ["cancellation", "cancel"],
    "unsubscribe": ["unsubscribe"],
    "failed_payment": ["failed_payment", "chargeback"],
    "negative_feedback": ["dissatisfaction", "negative_feedback", "low_satisfaction"],
    "risk_or_friction": ["risk", "friction"],
    "industry": ["industry", "sector"],
    "company_size": ["company_size", "employees", "employee_count"],
    "annual_revenue": ["annual_revenue"],
    "employee_count": ["employee_count"],
    "department": ["department"],
    "job_title": ["job_title", "title"],
    "seniority": ["seniority"],
    "decision_role": ["decision_role", "decision_maker", "influencer", "buyer", "gatekeeper", "user_role", "procurement"],
    "technology_stack": ["technology_stack", "crm", "erp", "stack"],
    "renewal_date": ["renewal_date"],
    "account_health": ["account_health", "health_score"],
}

NEGATIVE_POLARITY_WORDS = [
    "churn",
    "abandon",
    "return",
    "refund",
    "complaint",
    "support",
    "cancellation",
    "cancel",
    "unsubscribe",
    "risk",
    "recency",
    "inactive",
    "days_since",
    "failed",
    "chargeback",
    "negative",
]

POSITIVE_POLARITY_WORDS = [
    "revenue",
    "spend",
    "value",
    "orders",
    "purchases",
    "frequency",
    "sessions",
    "clicks",
    "open",
    "response",
    "conversion",
    "loyalty",
    "clv",
    "ltv",
    "profit",
    "satisfaction",
    "nps",
    "health",
]

SENSITIVE_NAME_HINTS = [
    "name",
    "email",
    "phone",
    "mobile",
    "address",
    "postcode",
    "postal_code",
    "latitude",
    "longitude",
    "gender",
    "health",
    "religion",
    "political",
    "ethnicity",
    "biometric",
]

